[features]
seeds = false
skip-lint = false
[programs.localnet]
agreement_program = "Fz3wjVypwyrY4a3fad9gTpDotqZg2bFBwEW4TkyruMTo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nomadbitcoin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
